services:
  app:
    build: .
    image: python-compose-task:task2
    container_name: python-compose-task2
    restart: unless-stopped
    ports:
    - "${HOST_BIND:-127.0.0.1}:${HOST_PORT:-8070}:${APP_PORT:-5000}"
    environment:
      APP_NAME: "${APP_NAME}"
      APP_ENV: "${APP_ENV}"
      APP_VERSION: "${APP_VERSION}"
      APP_PORT: "${APP_PORT}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      GUNICORN_WORKERS: "${GUNICORN_WORKERS}"
      GUNICORN_TIMEOUT: "${GUNICORN_TIMEOUT}"
      GUNICORN_LOG_LEVEL: "${GUNICORN_LOG_LEVEL}"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: task2-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  debug-redis-cli:
    image: redis:7-alpine
    container_name: task2-redis-cli
    profiles:
      - debug
    command: ["sh", "-c", "sleep infinity"]
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data:

