services:
  app:
    build: .
    image: python-compose-app:day11
    container_name: day11-python-app
    ports:
      - "${APP_PORT}:5000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: day11-redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  redis-data:
